CREATE TABLE IF NOT EXISTS "GarmentProfile" (
    "id" TEXT NOT NULL,
    "productAssetId" TEXT NOT NULL,
    "styleNo" TEXT,
    "productName" TEXT,
    "garmentCategory" TEXT,
    "collection" TEXT,
    "customer" TEXT,
    "brand" TEXT,
    "project" TEXT,
    "gender" TEXT,
    "ageGroup" TEXT,
    "tags" TEXT,
    "silhouette" TEXT,
    "fit" TEXT,
    "collarType" TEXT,
    "sleeveType" TEXT,
    "closureType" TEXT,
    "pocketDetails" TEXT,
    "hemDetails" TEXT,
    "waistbandDetails" TEXT,
    "liningStructure" TEXT,
    "interlining" TEXT,
    "shoulderPad" TEXT,
    "stitchDetails" TEXT,
    "constructionNote" TEXT,
    "mainFabric" TEXT,
    "contrastFabric" TEXT,
    "liningFabric" TEXT,
    "ribFabric" TEXT,
    "pocketingFabric" TEXT,
    "button" TEXT,
    "zipper" TEXT,
    "snapsEyelets" TEXT,
    "thread" TEXT,
    "labelTrims" TEXT,
    "packaging" TEXT,
    "materialUsage" TEXT,
    "substituteMaterials" TEXT,
    "sizeRange" TEXT,
    "baseSize" TEXT,
    "measurementPoints" TEXT,
    "sizeSpec" TEXT,
    "tolerance" TEXT,
    "gradingRule" TEXT,
    "shrinkageAllowance" TEXT,
    "garmentWeight" TEXT,
    "colorways" TEXT,
    "customerColorCodes" TEXT,
    "fabricColorCodes" TEXT,
    "garmentSku" TEXT,
    "barcode" TEXT,
    "availableSizes" TEXT,
    "colorImageNotes" TEXT,
    "moq" TEXT,
    "sampleVersion" TEXT,
    "patternMaker" TEXT,
    "merchandiser" TEXT,
    "owner" TEXT,
    "revisionHistory" TEXT,
    "fittingComments" TEXT,
    "customerComments" TEXT,
    "confirmedDate" TEXT,
    "techPackVersion" TEXT,
    "factory" TEXT,
    "orderQuantity" TEXT,
    "deliveryDate" TEXT,
    "targetCost" TEXT,
    "fobPrice" TEXT,
    "exwPrice" TEXT,
    "retailPrice" TEXT,
    "inspectionStandard" TEXT,
    "commonDefects" TEXT,
    "washFinishing" TEXT,
    "careLabel" TEXT,
    "complianceTests" TEXT,
    "packingMethod" TEXT,
    "cartonSpec" TEXT,
    "countryOfOrigin" TEXT,
    "qualityNote" TEXT,
    "updatedAt" BIGINT NOT NULL,
    "deletedAt" BIGINT,

    CONSTRAINT "GarmentProfile_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "GarmentProfile_productAssetId_key" ON "GarmentProfile"("productAssetId");
CREATE INDEX IF NOT EXISTS "GarmentProfile_styleNo_idx" ON "GarmentProfile"("styleNo");
CREATE INDEX IF NOT EXISTS "GarmentProfile_garmentCategory_idx" ON "GarmentProfile"("garmentCategory");
CREATE INDEX IF NOT EXISTS "GarmentProfile_customer_idx" ON "GarmentProfile"("customer");
CREATE INDEX IF NOT EXISTS "GarmentProfile_factory_idx" ON "GarmentProfile"("factory");

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'GarmentProfile_productAssetId_fkey' AND connamespace = 'public'::regnamespace) THEN
    ALTER TABLE "GarmentProfile" ADD CONSTRAINT "GarmentProfile_productAssetId_fkey" FOREIGN KEY ("productAssetId") REFERENCES "ProductAsset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
