import { readFileSync } from 'node:fs';
import { statSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

describe('MapLibreProductionGlobe', () => {
  it('uses a zoomed city route-map camera instead of the old full-globe camera', () => {
    const source = readFileSync(new URL('./MapLibreProductionGlobe.tsx', import.meta.url), 'utf8');

    expect(source).toContain('MAP_ROUTE_FALLBACK_CENTER: [number, number] = [120.5215, 31.8676]');
    expect(source).toContain('const MAP_ROUTE_CITY_ZOOM = 13.58');
    expect(source).toContain('const MAP_ROUTE_CITY_ZOOM_LOW = 13.05');
    expect(source).toContain('const MAP_MIN_RESPONSIVE_ZOOM = 12.55');
    expect(source).toContain('const MAP_MAX_RESPONSIVE_ZOOM = 14.08');
    expect(source).toContain('const MAP_ROUTE_CITY_PITCH = 58');
    expect(source).toContain('const MAP_ROUTE_CITY_BEARING = -24');
    expect(source).toContain('import { CityCoordinates }');
    expect(source).toContain('function resolveKnownCityFromText(value: unknown)');
    expect(source).toContain('function activeOrderLocation(order: Order): { lat: number; lon: number; label: string } | null');
    expect(source).toContain('return null;');
    expect(source).toContain('function resolveRouteMapCenter(orders: Order[]): [number, number]');
    expect(source).toContain('resolveKnownCityFromText(order.millAddress)');
    expect(source).toContain('resolveKnownCityFromText(order.consigneeAddress)');
    expect(source).toContain('resolveKnownCityFromText(order.customerAddress)');
    expect(source).toContain('const locatableOrders = useMemo(');
    expect(source).toContain('activeOrders.filter(order => Boolean(activeOrderLocation(order)))');
    expect(source).toContain('if (!location) return null;');
    expect(source).toContain('locatableOrders.length > 1');
    expect(source).not.toContain('NORMAL_ROUTE_LOCATIONS');
    expect(source).not.toContain('normalRouteFallbackLocation');
    expect(source).not.toContain('resolveLocation(fallback.label)');
    expect(source).toContain('center: routeCenterRef.current');
    expect(source).toContain('center: routeCenter');
    expect(source).toContain('resolveResponsiveGlobalZoom');
    expect(source).toContain('resolveMapCameraOffset');
    expect(source).toContain('resolveCameraOffsetForZoom');
    expect(source).toContain('offset: cameraOffset');
    expect(source).not.toContain('map.setPadding');
    expect(source).not.toContain('padding: cameraPadding');
    expect(source).toContain('viewportCenter?.width');
    expect(source).toContain('viewportCenter?.height');
    expect(source).toContain('Math.log2(shortSide / MAP_REFERENCE_SHORT_SIDE)');
    expect(source).toContain('pitch: MAP_ROUTE_CITY_PITCH');
    expect(source).toContain('bearing: MAP_ROUTE_CITY_BEARING');
    expect(source).toContain('zoom: 15.05');
    expect(source).toContain('pitch: 60');
    expect(source).toContain('const MAP_INTERACTION_MIN_ZOOM = 2.15');
    expect(source).toContain('minZoom: MAP_INTERACTION_MIN_ZOOM');
    expect(source).toContain("map.setProjection({ type: 'globe' })");
    expect(source).toContain('const [isMapStyled, setIsMapStyled] = useState(false)');
    expect(source).toContain('const hasPresentedInitialCameraRef = useRef(false)');
    expect(source).toContain('const presentInitialCamera = useCallback');
    expect(source).toContain('tourTargetsRef.current.length < 1');
    expect(source).toContain('duration: 0');
    expect(source).toContain("className={`absolute inset-0 transition-opacity duration-300 ${isMapVisible ? 'opacity-100' : 'opacity-0'}`}");
    expect(source).not.toContain('GLOBE_MAP_INTRO_DURATION_MS');
    expect(source).toContain('GLOBE_INTERACTION_RESUME_DELAY_MS');
    expect(source).toContain('const MAP_TOUR_OVERVIEW_ZOOM = 2.18');
    expect(source).toContain('const MAP_TOUR_CITY_ZOOM = 13.65');
    expect(source).toContain('const MAP_TOUR_FLY_DURATION_MS = 3600');
    expect(source).toContain('const scheduleTour = useCallback');
    expect(source).toContain('const availableTargets = tourTargetsRef.current');
    expect(source).toContain('isTourAnimatingRef.current = true');
    expect(source).toContain('zoom: MAP_TOUR_OVERVIEW_ZOOM');
    expect(source).toContain('liveMap.flyTo({');
    expect(source).toContain('curve: 1.55');
    expect(source).toContain('speed: 0.55');
    expect(source).toContain('easing: easeInOutCubic');
    expect(source).toContain('zoom: MAP_TOUR_CITY_ZOOM');
    expect(source).toContain('scheduleTour(MAP_TOUR_USER_RESUME_DELAY_MS)');
    expect(source).toContain('const isUserCameraEvent = (event?: { originalEvent?: unknown }) => Boolean(event?.originalEvent)');
    expect(source).toContain('map.on(\'move\', scheduleMarkerUpdate)');
    expect(source).toContain('window.requestAnimationFrame');
    expect(source).toContain('setMarkers(prev => {');
    expect(source).not.toContain('GLOBE_AUTO_ROTATE_SPEED * 1.4 * dt');
    expect(source).toContain('onRuntimeError');
    expect(source).toContain('const hasReachedInitialIdleRef = useRef(false)');
    expect(source).toContain('!hasReachedInitialIdleRef.current && !map.loaded()');
    expect(source).toContain('hasReachedInitialIdleRef.current = true');
  });

  it('renders frosted route nodes with a next-node control over connected route lines', () => {
    const source = readFileSync(new URL('./MapLibreProductionGlobe.tsx', import.meta.url), 'utf8');

    expect(source).toContain('const routeSegments = useMemo(() => {');
    expect(source).toContain('visibleMarkers.slice(0, -1).map');
    expect(source).toContain('locationLabel: label');
    expect(source).toContain('{marker.locationLabel}');
    expect(source).toContain('aria-label={`聚焦 ${marker.locationLabel} 节点`}');
    expect(source).toContain('id="bambook-route-map-line"');
    expect(source).toContain('rgb(var(--os-vnext-brand-blue-rgb) / 0.62)');
    expect(source).toContain('strokeDasharray="7 9"');
    expect(source).toContain('const mapOverlayControlClass = isDarkMode');
    expect(source).toContain('backdrop-blur-[15px] backdrop-saturate-[104%]');
    expect(source).toContain('shadow-none transition-[transform,background-color,color]');
    expect(source).toContain('text-[var(--os-vnext-brand-blue)]">→</span>');
    expect(source).toContain('const focusNextOrder = useCallback(() => {');
    expect(source).toContain('Next Node');
    expect(source).toContain('border-0');
    expect(source).not.toContain('shadow-2xl');
  });

  it('keeps style buildings globally and overlays real local building sources explicitly', () => {
    const source = readFileSync(new URL('./MapLibreProductionGlobe.tsx', import.meta.url), 'utf8');
    const envTypes = readFileSync(new URL('../vite-env.d.ts', import.meta.url), 'utf8');
    const cmabCore = JSON.parse(readFileSync(new URL('../public/data/zhangjiagang-cmab-buildings-core.geojson', import.meta.url), 'utf8'));
    const cmabRender = JSON.parse(readFileSync(new URL('../public/data/zhangjiagang-cmab-buildings-render.geojson', import.meta.url), 'utf8'));
    const buildingOverrides = JSON.parse(readFileSync(new URL('../public/data/zhangjiagang-building-overrides.geojson', import.meta.url), 'utf8'));
    const pmtilesStats = statSync(new URL('../public/data/zhangjiagang-cmab-buildings.pmtiles', import.meta.url));
    const gbaPmtilesStats = statSync(new URL('../public/data/zhangjiagang-gba-buildings.pmtiles', import.meta.url));

    expect(source).toContain('STYLE_BUILDINGS_LAYER_ID');
    expect(source).toContain("type: 'fill-extrusion'");
    expect(source).toContain("'fill-extrusion-height'");
    expect(source).toContain("'building:levels'");
    expect(source).toContain("import { Protocol as PmtilesProtocol } from 'pmtiles'");
    expect(source).toContain('REAL_BUILDINGS_SOURCE_ID');
    expect(source).toContain('REAL_BUILDINGS_LAYER_ID');
    expect(source).toContain('REAL_BUILDINGS_FOOTPRINT_LAYER_ID');
    expect(source).toContain('BUILDING_OVERRIDES_SOURCE_ID');
    expect(source).toContain('BUILDING_OVERRIDES_LAYER_ID');
    expect(source).toContain('BUILDING_OVERRIDES_FOOTPRINT_LAYER_ID');
    expect(source).not.toContain("const DEFAULT_REAL_BUILDINGS_FILE = 'data/zhangjiagang-cmab-buildings.pmtiles'");
    expect(source).toContain("const LOCAL_GBA_BUILDINGS_FILE = 'data/zhangjiagang-gba-buildings.pmtiles'");
    expect(source).toContain("const LOCAL_BUILDING_OVERRIDES_FILE = 'data/zhangjiagang-building-overrides.geojson'");
    expect(source).toContain("const DEFAULT_REAL_BUILDINGS_SOURCE_LAYER = 'buildings'");
    expect(source).toContain("const REPLACED_GBA_BUILDING_IDS = ['51458']");
    expect(source).toContain('const JUNMA_REPLACEMENT_AREA_POLYGON = {');
    expect(source).toContain("if (configuredUrl === 'off' || configuredUrl === 'none') return null");
    expect(source).toContain("const selectedUrl = configuredUrl || 'gba-local'");
    expect(source).toContain("selectedUrl === 'gba-local'");
    expect(source).toContain("getEnvValue('VITE_BAMBOOK_GLOBE_BUILDING_OVERRIDES_URL')");
    expect(source).toContain('function resolveBuildingOverridesUrl()');
    expect(source).toContain('function resolveBrowserUrl(pathOrUrl: string): string');
    expect(source).toContain('new URL(pathOrUrl, window.location.origin).toString()');
    expect(source).toContain('function isGeojsonBuildingsSource(url: string)');
    expect(source).toContain("type: 'geojson'");
    expect(source).toContain('data: url');
    expect(source).toContain("getEnvValue('VITE_BAMBOOK_GLOBE_REAL_BUILDINGS_URL')");
    expect(source).toContain("getEnvValue('VITE_BAMBOOK_GLOBE_REAL_BUILDINGS_SOURCE_LAYER')");
    expect(source).toContain('function ensurePmtilesProtocol()');
    expect(source).toContain("maplibregl.addProtocol('pmtiles', pmtilesProtocol.tile)");
    expect(source).toContain("url.startsWith('pmtiles://')");
    expect(source).toContain('return {');
    expect(source).toContain('url,');
    expect(source).toContain("endsWith('.pmtiles')");
    expect(source).toContain('url: `pmtiles://${url}`');
    expect(source).toContain("type: 'vector'");
    expect(source).toContain('tiles: [url]');
    expect(source).toContain("source: REAL_BUILDINGS_SOURCE_ID");
    expect(source).toContain('function replacedGbaBuildingFilter()');
    expect(source).toContain("filter: replacedGbaBuildingFilter()");
    expect(source).toContain("['within', JUNMA_REPLACEMENT_AREA_POLYGON]");
    expect(source).toContain("source: BUILDING_OVERRIDES_SOURCE_ID");
    expect(source).toContain("type: 'line'");
    expect(source).toContain('realBuildingFootprintPaint(isDarkMode)');
    expect(source).toContain('realBuildingExtrusionPaint(isDarkMode)');
    expect(source).toContain('buildingOverrideFootprintPaint(isDarkMode)');
    expect(source).toContain('buildingOverrideExtrusionPaint(isDarkMode)');
    expect(source).toContain('function addBuildingLayers(map: MapLibreMap, palette: WallpaperAccentPalette, isDarkMode: boolean): void');
    expect(source).toContain('addStyleBuildingLayer(map, palette, isDarkMode)');
    expect(source).toContain('if (resolveRealBuildingsConfig())');
    expect(source).not.toContain('map.removeLayer(STYLE_BUILDINGS_LAYER_ID)');
    expect(source).toContain('addRealBuildingLayer(map, palette, isDarkMode)');
    expect(source).toContain('addBuildingOverrideLayer(map, isDarkMode)');
    expect(source).toContain('addBuildingLayers(map, paletteRef.current, isDarkModeRef.current)');
    expect(source).toContain("['to-number', ['get', 'render_height']");
    expect(source).toContain("['to-number', ['get', 'real_height']");
    expect(source).toContain("['to-number', ['get', 'predicted_height']");
    expect(source).toContain("['to-number', ['get', 'height_mean']");
    expect(source).toContain('const displayHeightExpr = [');
    expect(source).toContain('100,\n    205');
    expect(source).toContain("...(usesGeojson ? {} : { 'source-layer': config.sourceLayer })");
    expect(source).toContain('addBuildingLayers(map, paletteRef.current, isDarkModeRef.current)');
    expect(source).toContain("['get', 'area_in_meters']");
    expect(envTypes).toContain('VITE_BAMBOOK_GLOBE_REAL_BUILDINGS_URL');
    expect(envTypes).toContain('VITE_BAMBOOK_GLOBE_REAL_BUILDINGS_SOURCE_LAYER');
    expect(envTypes).toContain('VITE_BAMBOOK_GLOBE_BUILDING_OVERRIDES_URL');
    expect(cmabCore.features.length).toBeGreaterThan(4000);
    expect(cmabCore.features.some((feature: any) => feature.properties?.id === 19650 && feature.properties?.height === 43.68)).toBe(true);
    expect(cmabRender.features.length).toBeGreaterThan(4400);
    expect(cmabRender.features.length).toBeLessThan(cmabCore.features.length);
    expect(cmabRender.features.some((feature: any) => feature.properties?.id === 19650 && feature.properties?.real_height === 43.68 && feature.properties?.render_height > 180)).toBe(true);
    expect(cmabRender.features.every((feature: any) => feature.properties?.source === 'CMAB')).toBe(true);
    expect(pmtilesStats.size).toBeGreaterThan(900_000);
    expect(gbaPmtilesStats.size).toBeGreaterThan(40_000_000);
    expect(buildingOverrides.features.length).toBe(2);
    expect(buildingOverrides.features.some((feature: any) => feature.properties?.id === 'junma-plaza-tower-a' && feature.properties?.height >= 100)).toBe(true);
    expect(buildingOverrides.features.some((feature: any) => feature.properties?.id === 'junma-plaza-tower-b' && feature.properties?.height >= 100)).toBe(true);
    expect(buildingOverrides.features.every((feature: any) => feature.properties?.source === 'BambookManualOverride')).toBe(true);
    expect(source).not.toContain('`${import.meta.env.BASE_URL}${DEFAULT_REAL_BUILDINGS_FILE}`');
    expect(source).not.toContain('CURATED_BUILDINGS_SOURCE_ID');
    expect(source).not.toContain('CURATED_BUILDINGS_LAYER_ID');
    expect(source).not.toContain('ZHANGJIAGANG_CURATED_BUILDINGS');
    expect(source).not.toContain('bambook-curated-city-massing');
    expect(source).not.toContain('function addCuratedBuildingLayer');
    expect(source).not.toContain('CUSTOM_BUILDINGS_LAYER_ID');
    expect(source).not.toContain('CUSTOM_BUILDINGS_SOURCE_ID');
    expect(source).not.toContain('addCustomBuildingLayer');
    expect(source).not.toContain('zhangjiagang_buildings.json');
    expect(source).not.toContain("getEnvValue('VITE_BAMBOOK_GLOBE_BUILDINGS_URL')");
  });

  it('binds the map surface and building colors to the wallpaper accent palette', () => {
    const source = readFileSync(new URL('./MapLibreProductionGlobe.tsx', import.meta.url), 'utf8');

    expect(source).toContain("import { defaultWallpaperAccentPalette, type WallpaperAccentPalette } from '../utils/wallpaperAccent'");
    expect(source).toContain('accentPalette?: WallpaperAccentPalette');
    expect(source).toContain('const palette = useMemo(() => accentPalette ?? defaultWallpaperAccentPalette(isDarkMode)');
    expect(source).toContain('const paletteRef = useRef<WallpaperAccentPalette>(palette)');
    expect(source).toContain('function resolveThemedMapColors(palette: WallpaperAccentPalette, isDarkMode: boolean)');
    expect(source).toContain("water: mixHexColor(palette.globeAtmosphere");
    expect(source).toContain("land: mixHexColor(palette.globeLand");
    expect(source).toContain("map.setPaintProperty(layer.id, 'background-color', colors.land)");
    expect(source).toContain("map.setPaintProperty(layer.id, 'fill-color', colors.water)");
    expect(source).toContain('THEME_MAP_LOCAL_FONT_FAMILY');
    expect(source).toContain("const THEME_MAP_TEXT_FONT_STACK = ['Urbanist Regular']");
    expect(source).toContain('localIdeographFontFamily: THEME_MAP_LOCAL_FONT_FAMILY');
    expect(source).toContain("map.setLayoutProperty(layer.id, 'text-font', resolveThemeMapTextFont");
    expect(source).toContain('function chinaChineseForeignEnglishTextFieldExpression()');
    expect(source).toContain("['get', 'name:zh-Hans']");
    expect(source).toContain("['get', 'iso_a2']");
    expect(source).toContain("'CHN'");
    expect(source).toContain('const CHINA_LABEL_AREA_POLYGON = {');
    expect(source).toContain("['within', CHINA_LABEL_AREA_POLYGON]");
    expect(source).toContain("['get', 'name:en']");
    expect(source).toContain("map.setLayoutProperty(layer.id, 'text-field', chinaChineseForeignEnglishTextFieldExpression())");
    expect(source).toContain("map.setPaintProperty(layer.id, 'text-halo-width', 0)");
    expect(source).toContain("map.setPaintProperty(layer.id, 'text-halo-blur', 0)");
    expect(source).toContain('applyBambookSkyStyle(map, palette');
    expect(source).toContain('applyBambookMapStyle(map, palette');
    expect(source).toContain('buildingExtrusionPaint(palette');
    expect(source).toContain('palette.globeAtmosphere');
    expect(source).toContain('palette.globeBorder');
    expect(source).toContain('palette.globeLand');
    expect(source).toContain('palette.globeLandRim');
    expect(source).toContain('function unifiedBuildingMaterialPaint(');
    expect(source).toContain("sourceHeightExpr: unknown[] = ['coalesce', ['to-number', ['get', 'render_height']], ['to-number', ['get', 'height']], 18]");
    expect(source).toContain('const materialOpacity = 0.86');
    expect(source).toContain("0,\n      '#9fb1c0'");
    expect(source).toContain("24,\n      '#7f96aa'");
    expect(source).toContain("80,\n      '#5e778d'");
    expect(source).toContain('return unifiedBuildingMaterialPaint(heightExpr, realHeightExpr)');
    expect(source).not.toContain("isDarkMode ? '#eef6fb' : '#ffffff'");
    expect(source).not.toContain("isDarkMode ? '#17304a' : '#91a7bc'");
  });

  it('pushes map label density to later zoom levels', () => {
    const source = readFileSync(new URL('./MapLibreProductionGlobe.tsx', import.meta.url), 'utf8');

    expect(source).toContain('const COUNTRY_LABEL_MIN_ZOOM = 3.35');
    expect(source).toContain('const STATE_LABEL_MIN_ZOOM = 5.75');
    expect(source).toContain('const CITY_LABEL_MIN_ZOOM = 6.45');
    expect(source).toContain('function resolveSymbolLayerZoomRange(layer: maplibregl.LayerSpecification)');
    expect(source).toContain("if (id.includes('country'))");
    expect(source).toContain("if (id.includes('state') || id.includes('province'))");
    expect(source).toContain("if (id.includes('city') || id.includes('capital'))");
    expect(source).toContain('map.setLayerZoomRange(layer.id, zoomRange.min, zoomRange.max ?? 24)');
    expect(source).not.toContain('bambook-continent-labels');
    expect(source).not.toContain('upsertContinentLabelLayer');
  });
});
