import { AgentRole, ToolRisk } from './types';

/**
 * agentLoop 主循环的边界常量。
 *
 * 这是整个 Agent 循环的"治理"层：所有上限都收口在这里，避免散落在多个文件里被各自硬编码。
 * 旧的 toolRuntime.runAgentToolCalls 上限 8 步、mcp/planner.planMcpToolCalls 上限 6 步、
 * mcp/executor.slice(0, 6) 这些数字将在 S2/S3 逐步迁移到引用这个常量。
 */
export const AGENT_LOOP_LIMITS = {
  /** 单次循环最多走多少步（含强制收尾）。 */
  maxSteps: 8,
  /** 单步内 LLM 可申请的工具调用数上限（防止 LLM 一次塞 50 个）。 */
  maxToolsPerStep: 3,
  /** 单个工具调用的硬超时（毫秒）。 */
  perToolTimeoutMs: 30_000,
  /** 整次循环的总耗时预算（毫秒）。超出后强制收尾，不再发起新的工具或 LLM 调用。 */
  totalBudgetMs: 90_000,
  /** LLM 输出 JSON 解析失败时的修复重试次数（"请严格按 schema 输出"）。 */
  llmRepairRetries: 1,
  /** 构建上下文时取最近多少轮对话历史（0=不含历史）。 */
  historyWindowSize: 8,
  /** 单个工具输出在 observation 中的字符上限（超出截断）。 */
  observationCharLimit: 6000,
  /** 整个 scratchpad observation 块的总字符预算（超出时从最早 step 压缩）。 */
  scratchpadCharBudget: 24_000,
} as const;

export type DefaultRoleDefinition = {
  id: AgentRole;
  name: string;
  description: string;
  permissions: string[];
};

export type DefaultToolDefinition = {
  id: string;
  name: string;
  scope: string;
  risk: ToolRisk;
  allowedRoles: AgentRole[];
  approvalRoles?: AgentRole[];
  description?: string;
  inputHint?: string;
};

export const DEFAULT_AGENT_ROLES: DefaultRoleDefinition[] = [
  {
    id: 'owner',
    name: 'Owner',
    description: 'System owner with full Agent OS administration and approval authority.',
    permissions: ['admin', 'knowledge:manage', 'tool:approve', 'memory:company:write'],
  },
  {
    id: 'admin',
    name: 'Admin',
    description: 'Administrator for users, knowledge, tools, and operational policies.',
    permissions: ['admin', 'knowledge:manage', 'tool:approve'],
  },
  {
    id: 'manager',
    name: 'Manager',
    description: 'Department manager who can inspect team data and approve risky actions.',
    permissions: ['team:read', 'tool:approve'],
  },
  {
    id: 'merchandiser',
    name: 'Merchandiser',
    description: 'Order follow-up role with access to orders, suppliers, samples, and logistics.',
    permissions: ['orders:read', 'orders:draft'],
  },
  {
    id: 'finance',
    name: 'Finance',
    description: 'Finance role for invoices, payments, contract amounts, and finance drafts.',
    permissions: ['finance:read', 'invoice:draft'],
  },
  {
    id: 'sales',
    name: 'Sales',
    description: 'Sales role for customers, quotes, order progress, and communication drafts.',
    permissions: ['sales:read', 'customer:draft'],
  },
  {
    id: 'viewer',
    name: 'Viewer',
    description: 'Read-only role limited to authorized knowledge and business records.',
    permissions: ['read'],
  },
  {
    id: 'agent_operator',
    name: 'Agent Operator',
    description: 'Automation operator who can start allowed jobs without bypassing approvals.',
    permissions: ['automation:run'],
  },
];

export const DEFAULT_AGENT_TOOLS: DefaultToolDefinition[] = [
  {
    id: 'products.count',
    name: 'Count Product Assets',
    scope: 'products',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'products.search',
    name: 'Search Product Assets',
    scope: 'products',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'products.query',
    name: 'Query Product Assets',
    scope: 'products',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'products.describe_schema',
    name: 'Describe Product Asset Schema',
    scope: 'products',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'dictionary.query',
    name: 'Query Business Dictionary',
    scope: 'products',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'records.query',
    name: 'Query Business Records',
    scope: 'products',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'products.get',
    name: 'Get Product Asset',
    scope: 'products',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'products.expand',
    name: 'Expand Product Asset Context',
    scope: 'products',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'orders.search',
    name: 'Search Orders',
    scope: 'orders',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales'],
  },
  {
    id: 'orders.query',
    name: 'Query Orders',
    scope: 'orders',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales'],
  },
  {
    id: 'orders.get',
    name: 'Get Order',
    scope: 'orders',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales'],
  },
  {
    id: 'orders.expand',
    name: 'Expand Order Context',
    scope: 'orders',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales'],
  },
  {
    id: 'relations.search',
    name: 'Search Relations',
    scope: 'relations',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'sales'],
  },
  {
    id: 'relations.query',
    name: 'Query Relations',
    scope: 'relations',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'sales'],
  },
  {
    id: 'relations.get',
    name: 'Get Relation',
    scope: 'relations',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'sales'],
  },
  {
    id: 'relations.expand',
    name: 'Expand Relation Context',
    scope: 'relations',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'sales'],
  },
  {
    id: 'relations.create',
    name: 'Create Relation',
    scope: 'relations',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'sales'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'knowledge.search',
    name: 'Search Knowledge Base',
    scope: 'knowledge',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'entities.search',
    name: 'Search Business Entities',
    scope: 'relations',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'entities.hydrate',
    name: 'Hydrate Business Entities',
    scope: 'relations',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'email.send',
    name: 'Send Email',
    scope: 'automation',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'agent_operator'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'knowledge.ingest',
    name: 'Ingest Knowledge',
    scope: 'knowledge',
    risk: 'medium',
    allowedRoles: ['owner', 'admin', 'manager'],
    approvalRoles: ['owner', 'admin', 'manager'] as AgentRole[],
  },

  // ─────────────────────────────────────────────────────────────────────
  // Step 2/3 additions — keep aligned with server/src/agent/mcp/manifest.ts.
  // RBAC: read-only tools follow the same allowedRoles as their scope's
  // existing query tools; mutations require manager+; high-risk mutations
  // (status transitions, convert-to-order) require explicit approval.
  // ─────────────────────────────────────────────────────────────────────

  // Development management — read-only
  {
    id: 'development.query',
    name: 'Query Development Cases',
    scope: 'development',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'development.get',
    name: 'Get Development Case',
    scope: 'development',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },

  // Development management — mutations (require approval)
  {
    id: 'development.update_stage',
    name: 'Update Development Stage',
    scope: 'development',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'development.convert_to_order',
    name: 'Convert Development Case to Order',
    scope: 'development',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },

  // Orders — read-only extensions
  {
    id: 'orders.list_by_status',
    name: 'List Orders by Status',
    scope: 'orders',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales'],
  },
  {
    id: 'orders.get_timeline',
    name: 'Get Order Timeline',
    scope: 'orders',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales'],
  },
  {
    id: 'orders.kanban',
    name: 'Order Kanban Summary',
    scope: 'orders',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales'],
  },

  // Orders — mutations (require approval)
  {
    id: 'orders.update_status',
    name: 'Update Order Status',
    scope: 'orders',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'orders.batch_status',
    name: 'Batch Update Order Status',
    scope: 'orders',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },

  // Garment-specific mutations
  {
    id: 'garment.update_size_breakdown',
    name: 'Update Garment Size Breakdown',
    scope: 'orders',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'garment.update_production_steps',
    name: 'Update Garment Production Steps',
    scope: 'orders',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },

  // Cross-module relationship graph
  {
    id: 'links.query',
    name: 'Query Entity Links',
    scope: 'relations',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  {
    id: 'links.expand_neighbors',
    name: 'Expand Entity Neighbors',
    scope: 'relations',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
  },
  // ─── 财务管理 (finance) — generated by scaffold-module.ts ───
  {
    id: 'finance.list_invoices',
    name: 'List Invoices',
    scope: 'finance',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser'],
  },
  {
    id: 'finance.get_invoice',
    name: 'Get Invoice',
    scope: 'finance',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser'],
  },
  {
    id: 'finance.list_vouchers',
    name: 'List Payment Vouchers',
    scope: 'finance',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser'],
  },
  {
    id: 'finance.get_voucher',
    name: 'Get Payment Voucher',
    scope: 'finance',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser'],
  },
  {
    id: 'finance.query_outstanding',
    name: 'Query Outstanding Balance',
    scope: 'finance',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser'],
  },
  {
    id: 'finance.get_aging',
    name: 'Get AR/AP Aging Report',
    scope: 'finance',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser'],
  },
  {
    id: 'finance.create_invoice',
    name: 'Create Invoice',
    scope: 'finance',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'finance'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'finance.create_voucher',
    name: 'Create Payment Voucher',
    scope: 'finance',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'finance'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'finance.apply_voucher_to_invoice',
    name: 'Apply Voucher To Invoice',
    scope: 'finance',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'finance'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  // ── Shipping (货运管理) ──
  {
    id: 'shipping.list_shipments',
    name: 'List Shipments',
    scope: 'shipping',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser', 'logistics'],
  },
  {
    id: 'shipping.get_shipment',
    name: 'Get Shipment',
    scope: 'shipping',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser', 'logistics'],
  },
  {
    id: 'shipping.create_shipment',
    name: 'Create Shipment',
    scope: 'shipping',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'logistics'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'shipping.update_tracking_status',
    name: 'Update Tracking Status',
    scope: 'shipping',
    risk: 'medium',
    allowedRoles: ['owner', 'admin', 'manager', 'logistics'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'shipping.scan_delays',
    name: 'Scan Delayed Shipments',
    scope: 'shipping',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser', 'logistics'],
  },
  // ── Quotations (报价管理) — C3 智能报价 ──
  {
    id: 'quotations.query',
    name: 'Query Quotations',
    scope: 'quotations',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'sales', 'merchandiser'],
  },
  {
    id: 'quotations.get',
    name: 'Get Quotation',
    scope: 'quotations',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'sales', 'merchandiser'],
  },
  // ── Customs (通关单证) — C3 LC 审单 ──
  {
    id: 'customs.query_lc',
    name: 'Query Letters of Credit',
    scope: 'customs',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser'],
  },
  {
    id: 'customs.get_lc',
    name: 'Get Letter of Credit',
    scope: 'customs',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser'],
  },
  // ── Email (邮件管理) — Phase 4a ──
  {
    id: 'email.list',
    name: 'List Emails',
    scope: 'email',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'logistics'],
  },
  {
    id: 'email.get',
    name: 'Get Email',
    scope: 'email',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'logistics'],
  },
  {
    id: 'email.search',
    name: 'Search Emails',
    scope: 'email',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'logistics'],
  },
  {
    id: 'email.sync',
    name: 'Sync Emails from IMAP',
    scope: 'email',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager'],
    approvalRoles: ['owner', 'admin'],
  },
  {
    id: 'email.link_to_order',
    name: 'Link Email to Order',
    scope: 'email',
    risk: 'medium',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'sales', 'logistics'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'email.ai_extract',
    name: 'AI Extract Email Fields',
    scope: 'email',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'sales'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'template.list',
    name: 'List Templates',
    scope: 'templates',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'logistics', 'viewer', 'agent_operator'],
  },
  {
    id: 'template.render',
    name: 'Render Template (HTML)',
    scope: 'templates',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'logistics', 'agent_operator'],
  },
  {
    id: 'template.render_pdf',
    name: 'Render Template to PDF',
    scope: 'templates',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'logistics', 'agent_operator'],
  },
  // ─── 生产管线 (production) — 10 阶段门禁引擎 ───
  {
    id: 'production.get_pipeline',
    name: 'Get Production Pipeline',
    scope: 'production',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'production_manager', 'factory', 'merchandiser', 'logistics', 'agent_operator'],
      description: '获取订单的 10 阶段生产管线状态——当前阶段、每阶段状态（pending/done/skipped）、检查清单、验货报告。',
    inputHint: '{ orderId: string }',
},
  {
    id: 'production.advance_stage',
    name: 'Advance Production Stage',
    scope: 'production',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'production_manager', 'factory', 'agent_operator'],
      description: '推进订单到下一个生产阶段。自动执行门禁检查（裁剪前四项 checklist / 产前样双签 / 验货阈值），检查不通过会拒绝推进。',
    inputHint: '{ orderId: string, stageKey: string, operator?: string, note?: string }',
},
  {
    id: 'production.save_checklist',
    name: 'Save Pre-Cut Checklist',
    scope: 'production',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'production_manager', 'factory', 'agent_operator'],
      description: '保存裁剪前检查清单（放码确认 / 用量确认 / 样板确认 / 产前会议）。四项全部 true 才能通过裁剪前门禁。',
    inputHint: '{ orderId: string, gradingConfirmed?: boolean, consumptionConfirmed?: boolean, patternConfirmed?: boolean, preProductionMeeting?: boolean, meetingNote?: string }',
},
  {
    id: 'production.save_inspection',
    name: 'Save Inspection Report',
    scope: 'production',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'production_manager', 'factory', 'agent_operator'],
      description: '保存验货报告——总数量、合格数量、业务方审批。合格率≥90% 且不合格率≤3% 才能通过验货门禁。',
    inputHint: '{ orderId: string, totalUnits?: number, passedUnits?: number, inspectedBy?: string, approvedByBusiness?: boolean }',
},
  {
    id: 'production.sign_stage',
    name: 'Sign Production Stage',
    scope: 'production',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'production_manager', 'factory', 'agent_operator'],
      description: '对生产阶段进行双签（生产部 / 业务部）。产前样阶段需要双方都签才能推进。',
    inputHint: "{ orderId: string, stageKey: string, signType: \"production\" | \"business\", signerId?: string }",
},
  {
    id: 'production.scan_alerts',
    name: 'Scan Production Alerts',
    scope: 'production',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'production_manager', 'factory', 'merchandiser', 'logistics', 'agent_operator'],
      description: '扫描所有活跃订单的生产预警——生产计划超期、延期通知窗口临近。返回预警列表含严重级别。',
    inputHint: '{}',
},
  // ── E3 NL 高频业务操作（下样品单 / 对账单）──
  {
    id: 'development.create',
    name: 'Create Development Case',
    scope: 'development',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  {
    id: 'finance.get_statement',
    name: 'Get Customer Statement',
    scope: 'finance',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser'],
  },
  {
    id: 'statement.send',
    name: 'Send Customer Statement',
    scope: 'finance',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'finance'],
    approvalRoles: ['owner', 'admin', 'manager'],
  },
  // ── Phase 4 Track G：Phase 2 八域只读查询工具（risk=low，免审批，无写库）──
  {
    id: 'moq.query_config',
    name: 'Query MOQ Config',
    scope: 'settings',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales', 'viewer', 'agent_operator'],
    description: '查询当前生效的 MOQ 最小起订量阈值配置（面料/成衣/Capsule），配置缺失时回落兜底常量；可选变更历史。',
    inputHint: '{ includeHistory?: boolean, historyLimit?: number }',
  },
  {
    id: 'order_changes.query',
    name: 'Query Order Change Requests',
    scope: 'orders',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales'],
    description: '查询 DR-010 订单变更/取消/暂停申请列表与详情（含关联订单与审批单快照）。',
    inputHint: '{ id?: string, orderId?: string, status?: string, requesterId?: string, limit?: number }',
  },
  {
    id: 'samples.query',
    name: 'Query Samples',
    scope: 'samples',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'sales', 'logistics'],
    description: '查询样品记录：面料寄船样/头缸样（可选发货资格）、早期生产样轮次、服装多轮样品（DR-008 双门禁）。',
    inputHint: '{ mode?: "fabric_shipment"|"early_production"|"garment_rounds", orderId?: string, caseId?: string, includeEligibility?: boolean }',
  },
  {
    id: 'qc.query_reports',
    name: 'Query QC Reports',
    scope: 'qc',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'sales', 'production_manager', 'factory'],
    description: '按订单查询 QC 报告列表（DR-029 服装链/面料链），可选 QC 出运资格判定。',
    inputHint: '{ orderId: string, includeEligibility?: boolean }',
  },
  {
    id: 'exceptions.query',
    name: 'Query Controlled Exceptions',
    scope: 'exceptions',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'sales'],
    description: '查询 DR-013 受控例外申请列表与详情（惰性对账审批结论）。',
    inputHint: '{ id?: string, status?: string, exceptionCategory?: string, requesterId?: string, limit?: number }',
  },
  {
    id: 'credit.query_status',
    name: 'Query Customer Credit Status',
    scope: 'credit',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'sales', 'merchandiser'],
    description: '查询客户信用状态（额度/占用/剩余/冻结门禁/最大逾期天数），可选信用历史时间线。',
    inputHint: '{ relationId: string, includeHistory?: boolean, historyLimit?: number }',
  },
  {
    id: 'internal_trade.query',
    name: 'Query Internal Transfers',
    scope: 'internal_trade',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    description: '查询 DR-005/033 内部供料单列表与详情（master + mirror + 解码载荷）。',
    inputHint: '{ id?: string, departmentId?: string, status?: string, garmentOrderId?: string, fabricOrderId?: string, limit?: number, offset?: number }',
  },
  {
    id: 'payment_requests.query',
    name: 'Query Payment Requests',
    scope: 'finance',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance'],
    description: '查询 DR-017 付款申请列表与详情（含关联审批单与付款凭证快照）。',
    inputHint: '{ id?: string, status?: string, paymentCategory?: string, applicantId?: string, limit?: number }',
  },
  // ── W4 收尾：Agent 工具缺口 5 类只读查询工具（risk=low，免审批，无写库）──
  {
    id: 'purchase_orders.query',
    name: 'Query Purchase Orders',
    scope: 'procurement',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance', 'production_manager'],
    description: '查询采购单列表（状态/供应商/日期窗/搜索）与详情（含行明细与到货记录）。',
    inputHint: '{ id?: string, status?: string, supplierRelationId?: string, dateFrom?: string, dateTo?: string, search?: string, limit?: number, offset?: number }',
  },
  {
    id: 'bom.query',
    name: 'Query BOMs',
    scope: 'bom',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'production_manager'],
    description: '查询 BOM 物料清单列表（状态/产品/订单/报价过滤）与详情（含行明细与成本估算）。',
    inputHint: '{ id?: string, status?: string, productAssetId?: string, orderId?: string, quotationId?: string, search?: string, limit?: number, offset?: number }',
  },
  {
    id: 'customs.query_tax_refunds',
    name: 'Query Tax Refunds',
    scope: 'customs',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance', 'logistics'],
    description: '查询出口退税记录列表（状态/报关单/订单/客户过滤）与详情（FOB/退税率/应退金额/审核信息）。',
    inputHint: '{ id?: string, status?: string, declarationId?: string, orderId?: string, relationId?: string, search?: string, limit?: number, offset?: number }',
  },
  {
    id: 'customs.query_declarations',
    name: 'Query Customs Declarations',
    scope: 'customs',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'logistics'],
    description: '查询报关单列表（类型/状态/运单/订单/客户过滤）与详情（含行明细）。',
    inputHint: '{ id?: string, type?: string, status?: string, shipmentId?: string, orderId?: string, relationId?: string, search?: string, limit?: number, offset?: number }',
  },
  {
    id: 'finance.query_allocations',
    name: 'Query Invoice Allocations',
    scope: 'finance',
    risk: 'low',
    allowedRoles: ['owner', 'admin', 'manager', 'finance'],
    description: '查询收付款核销明细列表（按发票/凭证过滤，含核销金额与日期）。',
    inputHint: '{ invoiceId?: string, voucherId?: string, limit?: number }',
  },
  // ── Phase 2 S3a：六新域写工具（draft→approval→commit，高风险需审批）──
  {
    id: 'order_changes.create',
    name: 'Create Order Change Request',
    scope: 'orders',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '创建订单变更/取消/暂停申请（DR-010），需提供订单ID、变更类型、前后快照、变更理由和影响说明。',
    inputHint: '{ orderId: string, changeType: "price"|"quantity"|"delivery"|"customer"|"product"|"cancel"|"pause", beforeSnapshot: object, afterDelta: object, changeReason: string, impactSummary: string, requesterId: string }',
  },
  {
    id: 'order_changes.withdraw',
    name: 'Withdraw Order Change Request',
    scope: 'orders',
    risk: 'medium',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '撤回订单变更申请（仅 Pending 状态且仅申请人本人可撤回）。',
    inputHint: '{ changeRequestId: string, actorId: string }',
  },
  {
    id: 'payment_requests.create',
    name: 'Create Payment Request',
    scope: 'finance',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'finance'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '创建付款申请（DR-017 先申请后付款），需提供收款方、金额、币种、付款性质、申请人。',
    inputHint: '{ supplierId?: string, supplierName?: string, totalAmount: number, currency: string, paymentCategory?: string, applicantId: string, reason?: string }',
  },
  {
    id: 'payment_requests.cancel',
    name: 'Cancel Payment Request',
    scope: 'finance',
    risk: 'medium',
    allowedRoles: ['owner', 'admin', 'manager', 'finance'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '作废付款申请（仅 Draft/Pending 且仅申请人本人可作废）。',
    inputHint: '{ paymentRequestId: string, actorId: string }',
  },
  {
    id: 'credit.freeze',
    name: 'Freeze Customer Credit',
    scope: 'credit',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'finance'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '人工冻结客户信用额度（冻结即新单门禁），理由必填（审计强制）。',
    inputHint: '{ relationId: string, reason: string, actorId: string }',
  },
  {
    id: 'credit.thaw',
    name: 'Thaw Customer Credit',
    scope: 'credit',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'finance'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '人工解冻客户信用额度，理由必填（审计强制）。',
    inputHint: '{ relationId: string, reason: string, actorId: string }',
  },
  {
    id: 'samples.create_round',
    name: 'Create Garment Sample Round',
    scope: 'samples',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'production_manager'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '创建服装样品轮次（DR-008/DR-029 双门禁），需提供开发案ID、目的、版本、材料配置。',
    inputHint: '{ caseId: string, input: { purpose: string, version: string, materialConfig: object }, actorId: string }',
  },
  {
    id: 'samples.submit_to_customer',
    name: 'Submit Sample To Customer',
    scope: 'samples',
    risk: 'medium',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'production_manager'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '提交样品给客户（内部门禁：QC 通过后方可提交），需提供轮次ID和寄送信息。',
    inputHint: '{ roundId: string, input: { courier?: string, trackingNo?: string, sentDate?: string }, actorId: string }',
  },
  {
    id: 'samples.register_customer_confirmation',
    name: 'Register Sample Customer Confirmation',
    scope: 'samples',
    risk: 'medium',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'production_manager'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '登记客户样品确认结论（approved/rejected/needs_revision），需提供轮次ID和确认结果。',
    inputHint: '{ roundId: string, input: { result: "approved"|"rejected"|"needs_revision", comment?: string }, actorId: string }',
  },
  {
    id: 'qc.review_garment_sample',
    name: 'QC Review Garment Sample',
    scope: 'qc',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'production_manager'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: 'QC 成衣链样品评审（DR-029），每轮报告独立不可覆盖，需提供订单ID、轮次、结论。',
    inputHint: '{ orderId: string, input: { level: "pp"|"top", round: number, conclusion: "pass"|"conditional"|"fail", opinion: string }, actorId: string }',
  },
  {
    id: 'qc.review_fabric_sample',
    name: 'QC Review Fabric Sample',
    scope: 'qc',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'production_manager'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: 'QC 面料链样品评审（DR-029），非 pass 必须提工厂技术调整要求，需提供订单ID、样品类型、结论。',
    inputHint: '{ orderId: string, input: { sampleKind: "SS"|"RC"|"EARLY_PRODUCTION", conclusion: "pass"|"conditional"|"fail", opinion: string, factoryAdjustment?: object }, actorId: string }',
  },
  {
    id: 'qc.sign_report',
    name: 'Sign QC Report',
    scope: 'qc',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'production_manager'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: 'QC 报告双签（产前样双签唯一入口），角色限 qc/business，签署留痕不可改写。',
    inputHint: '{ reportId: string, role: "qc"|"business", actorId: string }',
  },
  {
    id: 'internal_trade.create',
    name: 'Create Internal Transfer',
    scope: 'internal_trade',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '创建内部供料单（DR-005/033），需提供服装/面料订单、物料、数量、结算价、交期（结算价需 DR-006 审批）。',
    inputHint: '{ garmentOrderId: string, fabricOrderId: string, materialCode: string, quantity: number, settlementPrice: number, dueDate: string }',
  },
  {
    id: 'internal_trade.confirm',
    name: 'Confirm Internal Transfer',
    scope: 'internal_trade',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '确认内部供料单生效（生效门槛：结算价审批通过），需提供供料单ID和确认数量/交期。',
    inputHint: '{ transferId: string, actorId: string, confirmedQuantity?: number, confirmedDueDate?: string }',
  },
  // ── Phase 2 S3b：四存量域写工具（draft→approval→commit，高风险需审批）──
  {
    id: 'procurement.create',
    name: 'Create Purchase Order',
    scope: 'procurement',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '创建采购订单（PO），需提供币种、下单日期、行明细（供应商黑名单校验）。',
    inputHint: '{ poNumber?: string, supplierId: string, currency: string, orderDate: string, lines: Array<{ description: string, unit: string, quantity: number, unitPrice: number }> }',
  },
  {
    id: 'procurement.update_status',
    name: 'Update Purchase Order Status',
    scope: 'procurement',
    risk: 'medium',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '采购订单状态流转（Draft→Sent→Confirmed→PartiallyReceived/Received→Closed），目标状态不可手动设置 PartiallyReceived/Received。',
    inputHint: '{ purchaseOrderId: string, toStatus: string, reason?: string }',
  },
  {
    id: 'inventory.adjust_stock',
    name: 'Adjust Inventory Stock',
    scope: 'inventory',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'production_manager'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '库存变动登记（入库/出库/调拨/调整/锁定/解锁），需提供库存项、类型、数量（调拨需目标仓库）。',
    inputHint: '{ movement: { itemId: string, type: "Inbound"|"Outbound"|"Transfer"|"Adjustment"|"Lock"|"Unlock", quantity: number, targetWarehouseId?: string, reason?: string } }',
  },
  {
    id: 'quotation.create',
    name: 'Create Quotation',
    scope: 'quotations',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'sales'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '创建报价单（MOQ writeOnce 快照+双轨偏差审批），需提供币种、报价日期、行明细。',
    inputHint: '{ quotationNumber?: string, customerRelationId: string, currency: string, issueDate: string, lines: Array<{ description: string, unit: string, quantity: number, unitPrice: number }> }',
  },
  {
    id: 'quotation.update',
    name: 'Update Quotation',
    scope: 'quotations',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'sales'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '更新报价单（仅 Draft 状态可编辑），双轨快照与 MOQ 快照为 writeOnce 不可 patch。',
    inputHint: '{ quotationId: string, patch: { currency?: string, issueDate?: string, lines?: Array<...> } }',
  },
  {
    id: 'customs.register_lc',
    name: 'Register Letter of Credit',
    scope: 'customs',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'finance'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '登记信用证（首节点事件 Issued+EntityLink 同步），需提供证号、类型、金额、开证/效期。',
    inputHint: '{ lcNumber?: string, type: "Irrevocable"|"Revocable"|"Standby"|"Transferable", amount: number, currency: string, issueDate: string, expiryDate: string, applicant?: string, issuingBank?: string }',
  },
  {
    id: 'customs.update_declaration',
    name: 'Update Customs Declaration',
    scope: 'customs',
    risk: 'high',
    allowedRoles: ['owner', 'admin', 'manager', 'merchandiser', 'logistics'],
    approvalRoles: ['owner', 'admin', 'manager'],
    description: '更新报关单（仅 Draft 状态可编辑），需提供报关单ID和 patch。',
    inputHint: '{ declarationId: string, patch: { customsType?: "Export"|"Import", declarationDate?: string, ... } }',
  },
];
