// AUTO-GENERATED by scripts/generate-wallpaper-accent-samples.mjs
// Do NOT edit by hand. Run `node scripts/generate-wallpaper-accent-samples.mjs`
// whenever wallpapers under public/wallpapers/ change.

import type { WallpaperAccentRGB } from './wallpaperAccent';

export const BUILTIN_WALLPAPER_ACCENT_SAMPLES: Readonly<Record<string, WallpaperAccentRGB>> = {
  "/wallpapers/0076Aswbgy1h2840nwln9j31hc0u07t9.jpg": {
    "r": 59.3333,
    "g": 52.1806,
    "b": 54.3194
  },
  "/wallpapers/5.jpg": {
    "r": 33.8819,
    "g": 57.2153,
    "b": 93.8819
  },
  "/wallpapers/solid-burgundy.svg": {
    "r": 106,
    "g": 13,
    "b": 34
  },
  "/wallpapers/solid-dusk-violet.svg": {
    "r": 142,
    "g": 140,
    "b": 200
  },
  "/wallpapers/solid-forest-green.svg": {
    "r": 20,
    "g": 83,
    "b": 45
  },
  "/wallpapers/solid-graphite.svg": {
    "r": 46,
    "g": 58,
    "b": 70
  },
  "/wallpapers/solid-lagoon.svg": {
    "r": 124,
    "g": 183,
    "b": 199
  },
  "/wallpapers/solid-midnight-blue.svg": {
    "r": 15,
    "g": 23,
    "b": 42
  },
  "/wallpapers/solid-mint.svg": {
    "r": 167,
    "g": 243,
    "b": 208
  },
  "/wallpapers/solid-mist-blue.svg": {
    "r": 169,
    "g": 199,
    "b": 232
  },
  "/wallpapers/solid-mustard.svg": {
    "r": 224,
    "g": 180,
    "b": 64
  },
  "/wallpapers/solid-sage.svg": {
    "r": 156,
    "g": 175,
    "b": 158
  },
  "/wallpapers/solid-sakura-pink.svg": {
    "r": 255,
    "g": 228,
    "b": 230
  },
  "/wallpapers/solid-sunset.svg": {
    "r": 217,
    "g": 119,
    "b": 6
  },
  "/wallpapers/solid-warm-gray.svg": {
    "r": 184,
    "g": 178,
    "b": 168
  },
  "/wallpapers/test-solid-black.svg": {
    "r": 0,
    "g": 0,
    "b": 0
  },
  "/wallpapers/test-solid-brand-blue.svg": {
    "r": 74,
    "g": 144,
    "b": 226
  },
  "/wallpapers/test-solid-white.svg": {
    "r": 255,
    "g": 255,
    "b": 255
  },
  "/wallpapers/wallhaven-0qkg1q.jpg": {
    "r": 146.125,
    "g": 152.1875,
    "b": 156.4167
  },
  "/wallpapers/wallhaven-1kqvwg.jpg": {
    "r": 2.2361,
    "g": 65.1528,
    "b": 76.0972
  },
  "/wallpapers/wallhaven-48pwv2.jpg": {
    "r": 142.1597,
    "g": 164.7222,
    "b": 201.2222
  },
  "/wallpapers/wallhaven-4982k0.png": {
    "r": 37.1458,
    "g": 94.1181,
    "b": 111.7569
  },
  "/wallpapers/wallhaven-4dqgvj.jpg": {
    "r": 11.7361,
    "g": 69.7153,
    "b": 117.7014
  },
  "/wallpapers/wallhaven-6lw5ll.jpg": {
    "r": 96.1944,
    "g": 132.5,
    "b": 173.7917
  },
  "/wallpapers/wallhaven-966ev1.jpg": {
    "r": 87.6042,
    "g": 104.4722,
    "b": 134.4514
  },
  "/wallpapers/wallhaven-9mzg71.jpeg": {
    "r": 47.5764,
    "g": 60.1042,
    "b": 59.25
  },
  "/wallpapers/wallhaven-e8ejjw.jpg": {
    "r": 32.875,
    "g": 68,
    "b": 160.4028
  },
  "/wallpapers/wallhaven-g7j2jl.jpg": {
    "r": 146.5972,
    "g": 152.5833,
    "b": 156.9375
  },
  "/wallpapers/wallhaven-gw2zpq.jpg": {
    "r": 64.625,
    "g": 78.6528,
    "b": 87.3958
  },
  "/wallpapers/wallhaven-j3qovw.jpg": {
    "r": 32.5625,
    "g": 29.3819,
    "b": 31.9167
  },
  "/wallpapers/wallhaven-m9gop9.png": {
    "r": 69.4375,
    "g": 54.7708,
    "b": 70.6667
  },
  "/wallpapers/wallhaven-mdmrly.jpg": {
    "r": 70.5556,
    "g": 120.2569,
    "b": 141.7014
  },
  "/wallpapers/wallhaven-o58dm5.png": {
    "r": 90.5208,
    "g": 100.7639,
    "b": 108.1181
  },
  "/wallpapers/wallhaven-rqjrzq.jpg": {
    "r": 107.7292,
    "g": 119.9028,
    "b": 129.9306
  },
  "/wallpapers/wallhaven-w5m6yr.jpg": {
    "r": 64.7917,
    "g": 116.8889,
    "b": 158.3889
  },
  "/wallpapers/wallhaven-wq1q2r.jpeg": {
    "r": 58.2153,
    "g": 61.5069,
    "b": 70.4653
  },
  "/wallpapers/wallhaven-x6e13v.jpg": {
    "r": 54.7222,
    "g": 61.4722,
    "b": 65.1667
  },
  "/wallpapers/wallhaven-yqxzqx.jpg": {
    "r": 84.2986,
    "g": 92.1042,
    "b": 93.3194
  }
} as const;
