ALTER TABLE "FabricProfile" ADD COLUMN IF NOT EXISTS "moqValue" DOUBLE PRECISION;
ALTER TABLE "FabricProfile" ADD COLUMN IF NOT EXISTS "factoryMoqValue" DOUBLE PRECISION;
ALTER TABLE "FabricProfile" ADD COLUMN IF NOT EXISTS "sampleMoqValue" DOUBLE PRECISION;
ALTER TABLE "FabricProfile" ADD COLUMN IF NOT EXISTS "widthText" TEXT;
